### ISSUE TITLE
Showcase portfolio for NTBS does not display well on mobile device

### ISSUE THREAD

**Issue by jasmith1113** [karutaproject/karuta-frontend#60]
The process for sharing a showcase portfolio using Karuta 2.2 works well but when the portfolio (at least the one for NBTS) is displayed on a mobile device such as a phone or tablet, the navigation is confusing. The viewer sees the navigation options and can click on them to open different pages in the showcase portfolio, but the pages are located very far down across a black space, so the viewer does not know to scroll down to view the selected page. The viewer may be confused and think that the navigation is not working.

**Comment by olivier-gerbe** [comment]
Hi Janice,

It will be not perfect because the sidebar with the menu will be shorter than the page on a desktop but the display will be ok on tbalet and cellphone.

File: karuta-core/karuta/css/karuta.less

On line 152 and 730 replace height:100%; by height:auto;

Olivier

Le 3 nov. 2016 à 12:22, Janice Smith <notifications@github.com<mailto:notifications@github.com>> a écrit :


The process for sharing a showcase portfolio using Karuta 2.2 works well but when the portfolio (at least the one for NBTS) is displayed on a mobile device such as a phone or tablet, the navigation is confusing. The viewer sees the navigation options and can click on them to open different pages in the showcase portfolio, but the pages are located very far down across a black space, so the viewer does not know to scroll down to view the selected page. The viewer may be confused and think that the navigation is not working.

**Comment by olivier-gerbe** [comment]
Done
