### ISSUE TITLE
Semicolon data does not promote usability with English speaking users

### ISSUE THREAD

**Issue by jasmith1113** [karutaproject/karuta-frontend#62]
In order for English speaking users to create batch files to load users in Karuta, they must convert CSV files to use semicolons instead of commas. In addition, in order to use data exported from Karuta reports, they must convert semicolons back to commas for use in Excel. These extra steps are doable for the more technically inclined but will pose a roadblock for less technically able users or for any user that does not want to go through that many steps to load batch files or to export assessment data.

**Comment by darolmar** [comment]
I think in Sakai this is solved by using a property string at sakai.properties. Probably, we can provide a similar solution, that is, to include a property string specifying which separator is used.
Other option could be automatic detection, with several approximations:
1) We can think on using Locale. Once language is detected we will assume "," when the decimal separator is "." and ";" when the decimal separator is ",". I know this is can be tricky and quite primitive, but it will work most of the cases. Anyway, we have a problem still: the default value.
2) We can use Apache CSVFormat library: https://commons.apache.org/proper/commons-csv/apidocs/org/apache/commons/csv/CSVFormat.html and in this way, rely on an external library instead of implementing this feature. 

Personally, I really prefer the second one but I would love to hear suggestions, thoughts and any feedback you'll be so kind to provide.

**Comment by darolmar** [comment]
Now I see that there a configuration paramenter named csv_separator to do this. I'll explore automatic detection using Apache CSV lib.

**Comment by darolmar** [comment]
I see we use openCSV. The problem here is that you need to fix csv separator. I'm going to upgrade to univocity library. It provides automatic detection and that's a enhacement very valuable.

**Comment by olivier-gerbe** [comment]
Now csv separator is set in the backend configuration file : configKaruta.properties
